### ISSUE TITLE
Add a check to defaults option in state if it exists

### ISSUE THREAD

**Issue by vskubriev** [warpnet/salt-lint#258] opened 2021-07-27 11:44 UTC
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when case like this appears:

```
  file.managed:
    - source: {{ source_prefix }}/conf/named.conf.local
    - template: jinja
    - defaults:
      config: {{ config }}
      hostname: {{ srv }}
      cfg: {{ cfg }}
      prefix: {{ prefix }}
```

Options in `- defaults` array should be indented. Otherwise there is no default options in template and it is frustrating me.

**Describe the solution you'd like**
To be honest: I didn't know how to implement this case of check.

**Describe alternatives you've considered**
Manually check the code base.

**Comment by jbouter** [comment] 2023-01-13 13:42
This is a duplicate of #246 and will therefore be tracked in there

**Closed by jbouter** 2023-01-13 13:42 UTC
Labels: Type: Enhancement
